# Numpy 

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

In [5]:
import numpy as np

## create arrays using numpy
## create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2.shape)

(1, 5)


In [10]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
## identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### attributes of numpy array

In [15]:
## dimensions
arr2.ndim

2

In [ ]:
## size(number of elements)
arr2.size

10

In [ ]:
## arr.dtype
arr2.dtype ## may vary based on platform

dtype('int64')

In [ ]:
## itemsize
arr2.itemsize  ## may vary based on platform

8

### Numpy vectorised operations

In [20]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

### elemnt wise addition
print("addition",arr1+arr2)

### element wise subtraction
print("Subtraction",arr1-arr2)

### elemnt wise multiplication
print("Multiplication",arr1*arr2)

### elemnt wise division
print("division",arr1/arr2)

addition [11 22 33 44 55]
Subtraction [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]
division [0.1 0.1 0.1 0.1 0.1]


In [23]:
## universal functions
arr = np.array([2,3,4,5,6])
## sqr root
print(np.sqrt(arr))

## exponential
print(np.exp(arr))

## sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:

## array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n",arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
arr[0]

array([1, 2, 3, 4])

In [26]:
arr[0][0]

np.int64(1)

In [31]:
arr[1:,2:]
## elemnts in last 2 rows and last two columns

array([[ 7,  8],
       [11, 12]])

In [32]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [33]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [34]:
### modify array elements
arr[0][0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [35]:
arr[1:] = 100

In [36]:
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [37]:
arr[1:,1:3] = -1
print(arr)

[[100   2   3   4]
 [100  -1  -1 100]
 [100  -1  -1 100]]


In [38]:
### statistical concepts -- Normalization

## to have a mean of zero and standard deviation of 1
data = np.array([1,2,3,4,5])

## calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

## normalize the data
normalized_data = (data - mean) / std_dev
print("Normalised data : ",normalized_data)

Normalised data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [40]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

## mean
mean = np.mean(data)
print("Mean : ",mean)

## median
median = np.median(data)
print("Median : ",median)

## standard_deviation
std_dev = np.std(data)
print("Standard deviation : ",std_dev)

# variance
variance = np.var(data)
print("Variance : ",variance)

Mean :  5.5
Median :  5.5
Standard deviation :  2.8722813232690143
Variance :  8.25


In [41]:
### logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])

data > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [48]:
d = data[data > 5]
print(d)
d = data[(data > 5) & (data <= 8)]
print(d)

[ 6  7  8  9 10]
[6 7 8]
