## Logistic_implementation

In [118]:
import pandas as pd
import numpy as numpy
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [119]:
from sklearn.datasets import make_classification

In [120]:
## create the dataset
X,y = make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [121]:
X

array([[ 0.96479937, -0.06644898,  0.98676805, ..., -1.2101605 ,
        -0.62807677,  1.22727382],
       [-0.91651053, -0.56639459, -1.00861409, ..., -0.98453405,
         0.36389642,  0.20947008],
       [-0.10948373, -0.43277388, -0.4576493 , ..., -0.2463834 ,
        -1.05814521, -0.29737608],
       ...,
       [ 1.67463306,  1.75493307,  1.58615382, ...,  0.69272276,
        -1.50384972,  0.22526412],
       [-0.77860873, -0.83568901, -0.19484228, ..., -0.49735437,
         2.47213818,  0.86718741],
       [ 0.24845351, -1.0034389 ,  0.36046013, ...,  0.77323999,
         0.1857344 ,  1.41641179]])

In [122]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9
0,0.964799,-0.066449,0.986768,-0.358079,0.997266,1.181890,-1.615679,-1.210161,-0.628077,1.227274
1,-0.916511,-0.566395,-1.008614,0.831617,-1.176962,1.820544,1.752375,-0.984534,0.363896,0.209470
2,-0.109484,-0.432774,-0.457649,0.793818,-0.268646,-1.836360,1.239086,-0.246383,-1.058145,-0.297376
3,1.750412,2.023606,1.688159,0.006800,-1.607661,0.184741,-2.619427,-0.357445,-1.473127,-0.190039
4,-0.224726,-0.711303,-0.220778,0.117124,1.536061,0.597538,0.348645,-0.939156,0.175915,0.236224
...,...,...,...,...,...,...,...,...,...,...
995,-1.367638,1.462255,-1.154918,-0.290454,-0.413424,0.032396,1.545490,1.428760,1.687092,1.072542
996,-1.514876,-3.221016,-1.300744,0.395599,-0.527994,1.353069,1.777506,-1.680870,1.798510,0.034272
997,1.674633,1.754933,1.586154,0.018402,-1.514470,0.321593,-2.417694,0.692723,-1.503850,0.225264
998,-0.778609,-0.835689,-0.194842,1.097220,0.180071,-0.272933,-0.533188,-0.497354,2.472138,0.867187


In [123]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [124]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [125]:
### model training 
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()

In [126]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [127]:
y_pred = logistic.predict(X_test)
print(y_pred)

[0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 1
 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 0
 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 0 1 0 1 1 1 1
 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1
 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 1 0 1 1 0
 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 0 1 1 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1
 1 1 1 0]


In [128]:
### performance metrics
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score = accuracy_score(y_test,y_pred)
print(score)
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.8466666666666667
[[118  17]
 [ 29 136]]
              precision    recall  f1-score   support

           0       0.80      0.87      0.84       135
           1       0.89      0.82      0.86       165

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300



### Hyperparameter Tuning and Cross validation

In [129]:
model = LogisticRegression()
params = [
    {
        'solver': ['newton-cg', 'lbfgs', 'sag'],
        'penalty': ['l2'],
        'C': [100, 10, 1.0, 0.1, 0.01],
        'max_iter': [5000] # Increased to 5000
    },
    {
        'solver': ['liblinear'],
        'penalty': ['l1', 'l2'],
        'C': [100, 10, 1.0, 0.1, 0.01],
        'max_iter': [5000]
    },
    {
        'solver': ['saga'],
        'penalty': ['l1', 'l2'],
        'C': [100, 10, 1.0, 0.1, 0.01],
        'max_iter': [5000]
    },
    {
        'solver': ['saga'],
        'penalty': ['elasticnet'],
        'C': [100, 10, 1.0, 0.1, 0.01],
        'l1_ratio': [0.2, 0.5, 0.8], 
        'max_iter': [5000]
    }
]

In [130]:
##  GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()
from sklearn.model_selection import GridSearchCV 
grid = GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=1)


In [131]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=1,
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.01], 'max_iter': [5000],
                          'penalty': ['l2'],
                          'solver': ['newton-cg', 'lbfgs', 'sag']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'max_iter': [5000],
                          'penalty': ['l1', 'l2'], 'solver': ['liblinear']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'max_iter': [5000],
                          'penalty': ['l1', 'l2'], 'solver': ['saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.01],
                          'l1_ratio': [0.2, 0.5, 0.8], 'max_iter': [5000],
                          'penalty': ['elasticnet'], 'solver': ['saga']}],
             scoring='accuracy')

In [132]:
grid.fit(X_train,y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=1,
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.01], 'max_iter': [5000],
                          'penalty': ['l2'],
                          'solver': ['newton-cg', 'lbfgs', 'sag']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'max_iter': [5000],
                          'penalty': ['l1', 'l2'], 'solver': ['liblinear']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'max_iter': [5000],
                          'penalty': ['l1', 'l2'], 'solver': ['saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.01],
                          'l1_ratio': [0.2, 0.5, 0.8], 'max_iter': [5000],
                          'penalty': ['elasticnet'], 'solver': ['saga']}],
             scoring='accuracy')

In [133]:
grid.best_params_

{'C': 0.01, 'max_iter': 5000, 'penalty': 'l1', 'solver': 'liblinear'}

In [134]:
grid.best_score_

np.float64(0.8771428571428572)

In [135]:
y_pred = grid.predict(X_test)

In [136]:
score = accuracy_score(y_test,y_pred)
print(score)
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.8566666666666667
[[122  13]
 [ 30 135]]
              precision    recall  f1-score   support

           0       0.80      0.90      0.85       135
           1       0.91      0.82      0.86       165

    accuracy                           0.86       300
   macro avg       0.86      0.86      0.86       300
weighted avg       0.86      0.86      0.86       300



## Randomized Search cv

In [138]:
from sklearn.model_selection import RandomizedSearchCV
model = LogisticRegression()
randomcv =RandomizedSearchCV(estimator = model,param_distributions=params,cv = 5,scoring = 'accuracy')

In [139]:
randomcv.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions=[{'C': [100, 10, 1.0, 0.1, 0.01],
                                         'max_iter': [5000], 'penalty': ['l2'],
                                         'solver': ['newton-cg', 'lbfgs',
                                                    'sag']},
                                        {'C': [100, 10, 1.0, 0.1, 0.01],
                                         'max_iter': [5000],
                                         'penalty': ['l1', 'l2'],
                                         'solver': ['liblinear']},
                                        {'C': [100, 10, 1.0, 0.1, 0.01],
                                         'max_iter': [5000],
                                         'penalty': ['l1', 'l2'],
                                         'solver': ['saga']},
                                        {'C': [100, 10, 1.0, 0.1, 0.01],
                                         'l1_ratio': [0.2, 0.5, 0.8],
                                         'max_iter': [5000],
                                         'penalty': ['elasticnet'],
                                         'solver': ['saga']}],
                   scoring='accuracy')

In [140]:
randomcv.best_score_

np.float64(0.8742857142857143)

In [141]:
randomcv.best_params_

{'solver': 'lbfgs', 'penalty': 'l2', 'max_iter': 5000, 'C': 0.1}

In [142]:
y_pred = randomcv.predict(X_test)

In [143]:
score = accuracy_score(y_test,y_pred)
print(score)
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.8533333333333334
[[121  14]
 [ 30 135]]
              precision    recall  f1-score   support

           0       0.80      0.90      0.85       135
           1       0.91      0.82      0.86       165

    accuracy                           0.85       300
   macro avg       0.85      0.86      0.85       300
weighted avg       0.86      0.85      0.85       300

